using System.Text.Json;
using Blacklabel.Domain.Entities;
using Blacklabel.Domain.Enums;

namespace Blacklabel.Infrastructure.Persistence.Seed;

public static class AdditiveSeedData
{
    // Common names used on Turkish ingredient labels in place of the E-code, for OCR matching (§6).
    private static readonly Dictionary<string, string[]> SynonymOverrides = new()
    {
        ["E100"] = new[] { "kurkumin", "curcumin" },
        ["E101"] = new[] { "riboflavin" },
        ["E102"] = new[] { "tartrazin", "tartrazine" },
        ["E110"] = new[] { "gün batımı sarısı", "sunset yellow" },
        ["E120"] = new[] { "koşinil", "cochineal", "karmin", "carmine" },
        ["E122"] = new[] { "azorubin", "carmoisine" },
        ["E124"] = new[] { "ponso 4r", "ponceau 4r" },
        ["E129"] = new[] { "allura kırmızısı", "allura red" },
        ["E150a"] = new[] { "karamel", "caramel" },
        ["E171"] = new[] { "titanyum dioksit", "titanium dioxide" },
        ["E200"] = new[] { "sorbik asit", "sorbic acid" },
        ["E202"] = new[] { "potasyum sorbat", "potassium sorbate" },
        ["E211"] = new[] { "sodyum benzoat", "sodium benzoate" },
        ["E220"] = new[] { "kükürt dioksit", "sulphur dioxide", "sulfur dioxide" },
        ["E250"] = new[] { "sodyum nitrit", "sodium nitrite" },
        ["E251"] = new[] { "sodyum nitrat", "sodium nitrate" },
        ["E260"] = new[] { "asetik asit", "acetic acid" },
        ["E270"] = new[] { "laktik asit", "lactic acid" },
        ["E296"] = new[] { "malik asit", "malic acid" },
        ["E297"] = new[] { "fumarik asit", "fumaric acid" },
        ["E300"] = new[] { "askorbik asit", "ascorbic acid", "c vitamini", "vitamin c" },
        ["E319"] = new[] { "tbhq" },
        ["E320"] = new[] { "bha" },
        ["E321"] = new[] { "bht" },
        ["E322"] = new[] { "lesitin", "lecithin", "soya lesitini", "soy lecithin" },
        ["E330"] = new[] { "sitrik asit", "citric acid" },
        ["E334"] = new[] { "tartarik asit", "tartaric acid" },
        ["E339"] = new[] { "sodyum fosfat", "sodium phosphate" },
        ["E401"] = new[] { "sodyum aljinat", "sodium alginate" },
        ["E406"] = new[] { "agar", "agar agar" },
        ["E407"] = new[] { "karragenan", "carrageenan" },
        ["E412"] = new[] { "guar gamı", "guar gum" },
        ["E415"] = new[] { "ksantan gamı", "xanthan gum" },
        ["E420"] = new[] { "sorbitol" },
        ["E421"] = new[] { "mannitol" },
        ["E440"] = new[] { "pektin", "pectin" },
        ["E471"] = new[] { "mono ve digliseritler", "mono- and diglycerides" },
        ["E500"] = new[] { "sodyum bikarbonat", "sodium bicarbonate", "karbonat" },
        ["E621"] = new[] { "monosodyum glutamat", "monosodium glutamate", "msg" },
        ["E950"] = new[] { "asesülfam k", "acesulfame k", "acesulfame potassium" },
        ["E951"] = new[] { "aspartam", "aspartame" },
        ["E955"] = new[] { "sükraloz", "sucralose" },
        ["E960"] = new[] { "stevia", "steviol glikozitleri", "steviol glycosides" },
        ["E967"] = new[] { "ksilitol", "xylitol" },
    };

    public static IReadOnlyList<Additive> Get()
    {
        var additives = new List<Additive>
        {
        // Colorants (E100-E180)
        Create("E100", "Kurkumin", "Curcumin", AdditiveCategory.Colorant, 0,
            "Zerdeçaldan elde edilen doğal sarı renklendirici.",
            "Natural yellow colorant derived from turmeric.",
            "EFSA ADI: belirtilmemiş"),
        Create("E101", "Riboflavin (B2 Vitamini)", "Riboflavin (Vitamin B2)", AdditiveCategory.Colorant, 0,
            "Doğal olarak birçok gıdada bulunan sarı renkli bir vitamin; renklendirici olarak da kullanılır.",
            "A yellow vitamin naturally present in many foods; also used as a colorant.",
            null),
        Create("E102", "Tartrazin", "Tartrazine", AdditiveCategory.Colorant, 3,
            "Sentetik azo boyar madde. AB mevzuatına göre ürün etiketinde 'çocukların davranış ve dikkat düzeyi üzerinde olumsuz etkileri olabilir' uyarısı bulunması zorunludur.",
            "Synthetic azo dye. Under EU regulation, products containing it must carry the warning 'may have an adverse effect on activity and attention in children'.",
            "AB Yönetmeliği 1333/2008, Ek V"),
        Create("E104", "Kinolin Sarısı", "Quinoline Yellow", AdditiveCategory.Colorant, 3,
            "Sentetik sarı renklendirici. AB mevzuatına göre çocuklarda davranış/dikkat uyarısı taşıması zorunlu altı boyardan biridir.",
            "Synthetic yellow colorant. One of the six dyes that must carry the EU child behaviour/attention warning label.",
            "AB Yönetmeliği 1333/2008, Ek V"),
        Create("E110", "Gün Batımı Sarısı FCF", "Sunset Yellow FCF", AdditiveCategory.Colorant, 3,
            "Sentetik azo boyar madde. AB mevzuatına göre çocuklarda davranış/dikkat uyarısı taşıması zorunludur.",
            "Synthetic azo dye. Must carry the EU child behaviour/attention warning label.",
            "AB Yönetmeliği 1333/2008, Ek V"),
        Create("E120", "Koşinil / Karminik Asit", "Cochineal / Carminic Acid", AdditiveCategory.Colorant, 1,
            "Koşinil böceğinden elde edilen kırmızı renklendirici. Vegan değildir; nadiren alerjik reaksiyon bildirilmiştir.",
            "Red colorant derived from the cochineal insect. Not vegan; allergic reactions have rarely been reported.",
            null),
        Create("E122", "Azorubin (Karmoisin)", "Azorubine (Carmoisine)", AdditiveCategory.Colorant, 3,
            "Sentetik azo boyar madde. AB mevzuatına göre çocuklarda davranış/dikkat uyarısı taşıması zorunludur.",
            "Synthetic azo dye. Must carry the EU child behaviour/attention warning label.",
            "AB Yönetmeliği 1333/2008, Ek V"),
        Create("E124", "Ponso 4R", "Ponceau 4R", AdditiveCategory.Colorant, 3,
            "Sentetik azo boyar madde. AB mevzuatına göre çocuklarda davranış/dikkat uyarısı taşıması zorunludur.",
            "Synthetic azo dye. Must carry the EU child behaviour/attention warning label.",
            "AB Yönetmeliği 1333/2008, Ek V"),
        Create("E127", "Eritrosin", "Erythrosine", AdditiveCategory.Colorant, 2,
            "İyot içeren kırmızı renklendirici; kullanım alanı sınırlıdır. Tiroid hassasiyeti olanlarda dikkat edilmesi önerilir.",
            "Iodine-containing red colorant with restricted permitted uses. Caution is advised for those with thyroid sensitivity.",
            "EFSA kullanım kısıtlaması mevcuttur"),
        Create("E129", "Allura Kırmızısı AC", "Allura Red AC", AdditiveCategory.Colorant, 3,
            "Sentetik azo boyar madde. AB mevzuatına göre çocuklarda davranış/dikkat uyarısı taşıması zorunludur.",
            "Synthetic azo dye. Must carry the EU child behaviour/attention warning label.",
            "AB Yönetmeliği 1333/2008, Ek V"),
        Create("E131", "Patent Mavisi V", "Patent Blue V", AdditiveCategory.Colorant, 1,
            "Sentetik mavi renklendirici. Nadiren alerjik reaksiyonlarla ilişkilendirilmiştir.",
            "Synthetic blue colorant. Rarely associated with allergic reactions.",
            null),
        Create("E132", "İndigotin", "Indigotine", AdditiveCategory.Colorant, 1,
            "Sentetik mavi renklendirici, genel kullanımda güvenli kabul edilir.",
            "Synthetic blue colorant, generally recognized as safe within permitted uses.",
            null),
        Create("E133", "Parlak Mavi FCF", "Brilliant Blue FCF", AdditiveCategory.Colorant, 1,
            "Sentetik mavi renklendirici, genel kullanımda güvenli kabul edilir.",
            "Synthetic blue colorant, generally recognized as safe within permitted uses.",
            null),
        Create("E140", "Klorofiller", "Chlorophylls", AdditiveCategory.Colorant, 0,
            "Bitkilerden elde edilen doğal yeşil renklendirici.",
            "Natural green colorant extracted from plants.",
            null),
        Create("E150a", "Sade Karamel", "Plain Caramel", AdditiveCategory.Colorant, 0,
            "Şekerin ısıyla karamelize edilmesiyle elde edilen kahverengi renklendirici.",
            "Brown colorant produced by heat-caramelizing sugar.",
            null),
        Create("E150d", "Sülfitli-Amonyaklı Karamel", "Sulphite Ammonia Caramel", AdditiveCategory.Colorant, 1,
            "Kolalı içeceklerde yaygın kullanılan karamel türü. EFSA, üretim sürecinde iz miktarda oluşabilecek 4-MEI bileşiği için günlük alım limiti belirlemiştir.",
            "Caramel type commonly used in cola drinks. EFSA has set a daily intake limit for trace 4-MEI that may form during production.",
            "EFSA ADI: 4-MEI için 0.2 mg/kg vücut ağırlığı"),
        Create("E160a", "Karotenler", "Carotenes", AdditiveCategory.Colorant, 0,
            "Havuç gibi bitkilerde doğal olarak bulunan turuncu-sarı renklendirici.",
            "Orange-yellow colorant naturally found in plants such as carrots.",
            null),
        Create("E160c", "Paprika Ekstraktı", "Paprika Extract", AdditiveCategory.Colorant, 0,
            "Kırmızı biberden elde edilen doğal turuncu-kırmızı renklendirici.",
            "Natural orange-red colorant extracted from paprika peppers.",
            null),
        Create("E162", "Pancar Kırmızısı (Betanin)", "Beetroot Red (Betanin)", AdditiveCategory.Colorant, 0,
            "Kırmızı pancardan elde edilen doğal kırmızı renklendirici.",
            "Natural red colorant extracted from red beetroot.",
            null),
        Create("E163", "Antosiyaninler", "Anthocyanins", AdditiveCategory.Colorant, 0,
            "Üzüm kabuğu gibi kaynaklardan elde edilen doğal kırmızı-mor renklendirici grubu.",
            "Group of natural red-purple colorants extracted from sources such as grape skin.",
            null),
        Create("E171", "Titanyum Dioksit", "Titanium Dioxide", AdditiveCategory.Colorant, 2,
            "Beyaz renklendirici. EFSA'nın 2021 değerlendirmesinde genotoksisite riski dışlanamadığı belirtilmiş ve AB'de 2022 yılından itibaren gıdalarda kullanımı yasaklanmıştır.",
            "White colorant. EFSA's 2021 opinion could not rule out a genotoxicity concern, and the EU has prohibited its use in food since 2022.",
            "EFSA 2021 görüşü; AB Yönetmeliği 2022/63"),
        Create("E172", "Demir Oksitleri", "Iron Oxides", AdditiveCategory.Colorant, 0,
            "Kahverengi-kırmızı-siyah tonlarda kullanılan mineral kökenli renklendirici.",
            "Mineral-derived colorant used for brown, red and black tones.",
            null),
        Create("E173", "Alüminyum", "Aluminium", AdditiveCategory.Colorant, 1,
            "Yüzey kaplama/dekorasyon amaçlı kullanılan metalik renklendirici. Kullanım alanı sınırlıdır.",
            "Metallic colorant used for surface coating and decoration, with restricted permitted uses.",
            null),
        Create("E180", "Litolrubin BK", "Litholrubine BK", AdditiveCategory.Colorant, 1,
            "Bazı peynir kabuklarında kullanılan sentetik kırmızı renklendirici; kullanım alanı sınırlıdır.",
            "Synthetic red colorant used in some cheese rinds, with restricted permitted uses.",
            null),

        // Preservatives (E200-E299)
        Create("E200", "Sorbik Asit", "Sorbic Acid", AdditiveCategory.Preservative, 0,
            "Küf ve mayaların üremesini engelleyen, doğada da bulunan bir koruyucu.",
            "A naturally occurring preservative that inhibits the growth of mould and yeast.",
            null),
        Create("E202", "Potasyum Sorbat", "Potassium Sorbate", AdditiveCategory.Preservative, 0,
            "Sorbik asidin tuzu; küf ve maya oluşumunu önlemek için yaygın kullanılan bir koruyucu.",
            "A salt of sorbic acid; a widely used preservative against mould and yeast.",
            null),
        Create("E203", "Kalsiyum Sorbat", "Calcium Sorbate", AdditiveCategory.Preservative, 0,
            "Sorbik asidin tuzu; koruyucu olarak kullanılır.",
            "A salt of sorbic acid used as a preservative.",
            null),
        Create("E210", "Benzoik Asit", "Benzoic Acid", AdditiveCategory.Preservative, 1,
            "Bakteri ve mantar üremesini engelleyen bir koruyucu. EFSA günlük alım limiti belirlemiştir.",
            "A preservative that inhibits bacterial and fungal growth. EFSA has set a daily intake limit.",
            "EFSA ADI: 5 mg/kg vücut ağırlığı"),
        Create("E211", "Sodyum Benzoat", "Sodium Benzoate", AdditiveCategory.Preservative, 2,
            "Yaygın kullanılan bir koruyucu. C vitamini ile birlikte ve ısı/ışığa maruz kalındığında iz miktarda benzen oluşabileceği bazı çalışmalarda gösterilmiştir; EFSA günlük alım limiti belirlemiştir.",
            "A widely used preservative. Some studies have shown trace benzene can form when combined with vitamin C under heat or light exposure; EFSA has set a daily intake limit.",
            "EFSA ADI: 5 mg/kg vücut ağırlığı"),
        Create("E212", "Potasyum Benzoat", "Potassium Benzoate", AdditiveCategory.Preservative, 1,
            "Benzoik asidin tuzu; koruyucu olarak kullanılır.",
            "A salt of benzoic acid used as a preservative.",
            "EFSA ADI: 5 mg/kg vücut ağırlığı"),
        Create("E220", "Kükürt Dioksit", "Sulphur Dioxide", AdditiveCategory.Preservative, 2,
            "Kuru meyve ve şaraplarda yaygın koruyucu. Hassasiyeti olan kişilerde, özellikle astımlılarda solunum yolu reaksiyonları bildirilmiştir; AB'de zorunlu alerjen etiketlemesi gerektirir.",
            "A common preservative in dried fruit and wine. Respiratory reactions have been reported in sensitive individuals, particularly people with asthma; mandatory allergen labelling applies in the EU.",
            "AB alerjen listesi"),
        Create("E221", "Sodyum Sülfit", "Sodium Sulphite", AdditiveCategory.Preservative, 2,
            "Sülfit grubu bir koruyucu. Hassasiyeti olanlarda reaksiyonlara neden olabilir; alerjen etiketlemesi zorunludur.",
            "A sulphite-group preservative. May cause reactions in sensitive individuals; allergen labelling is mandatory.",
            "AB alerjen listesi"),
        Create("E222", "Sodyum Hidrojen Sülfit", "Sodium Hydrogen Sulphite", AdditiveCategory.Preservative, 2,
            "Sülfit grubu bir koruyucu. Hassasiyeti olanlarda reaksiyonlara neden olabilir; alerjen etiketlemesi zorunludur.",
            "A sulphite-group preservative. May cause reactions in sensitive individuals; allergen labelling is mandatory.",
            "AB alerjen listesi"),
        Create("E223", "Sodyum Metabisülfit", "Sodium Metabisulphite", AdditiveCategory.Preservative, 2,
            "Sülfit grubu bir koruyucu. Hassasiyeti olanlarda, özellikle astımlılarda reaksiyonlara neden olabilir; alerjen etiketlemesi zorunludur.",
            "A sulphite-group preservative. May cause reactions in sensitive individuals, particularly people with asthma; allergen labelling is mandatory.",
            "AB alerjen listesi"),
        Create("E224", "Potasyum Metabisülfit", "Potassium Metabisulphite", AdditiveCategory.Preservative, 2,
            "Sülfit grubu bir koruyucu. Hassasiyeti olanlarda reaksiyonlara neden olabilir; alerjen etiketlemesi zorunludur.",
            "A sulphite-group preservative. May cause reactions in sensitive individuals; allergen labelling is mandatory.",
            "AB alerjen listesi"),
        Create("E249", "Potasyum Nitrit", "Potassium Nitrite", AdditiveCategory.Preservative, 2,
            "İşlenmiş et ürünlerinde botulizmi önlemek için kullanılan bir koruyucu. EFSA 2017 değerlendirmesinde günlük alım limitini düşürmüştür; nitrozamin oluşumu bazı çalışmalarda incelenmiştir.",
            "A preservative used in processed meat products to prevent botulism. EFSA's 2017 review lowered the acceptable daily intake; nitrosamine formation has been examined in some studies.",
            "EFSA 2017 değerlendirmesi"),
        Create("E250", "Sodyum Nitrit", "Sodium Nitrite", AdditiveCategory.Preservative, 2,
            "İşlenmiş et ürünlerinde (sucuk, salam, sosis) botulizmi önlemek için kullanılan bir koruyucu. EFSA 2017 değerlendirmesinde günlük alım limitini düşürmüştür; nitrozamin oluşumu bazı çalışmalarda incelenmiştir.",
            "A preservative used in processed meats (sausage, salami) to prevent botulism. EFSA's 2017 review lowered the acceptable daily intake; nitrosamine formation has been examined in some studies.",
            "EFSA 2017 değerlendirmesi"),
        Create("E251", "Sodyum Nitrat", "Sodium Nitrate", AdditiveCategory.Preservative, 2,
            "İşlenmiş et ve bazı peynirlerde kullanılan bir koruyucu. EFSA günlük alım limiti belirlemiştir.",
            "A preservative used in processed meats and some cheeses. EFSA has set a daily intake limit.",
            "EFSA 2017 değerlendirmesi"),
        Create("E252", "Potasyum Nitrat", "Potassium Nitrate", AdditiveCategory.Preservative, 2,
            "İşlenmiş et ürünlerinde kullanılan bir koruyucu. EFSA günlük alım limiti belirlemiştir.",
            "A preservative used in processed meat products. EFSA has set a daily intake limit.",
            "EFSA 2017 değerlendirmesi"),
        Create("E260", "Asetik Asit", "Acetic Acid", AdditiveCategory.Preservative, 0,
            "Sirkenin ana bileşeni; koruyucu ve asitlik düzenleyici olarak kullanılır.",
            "The main component of vinegar; used as a preservative and acidity regulator.",
            null),
        Create("E261", "Potasyum Asetat", "Potassium Acetate", AdditiveCategory.Preservative, 0,
            "Asetik asidin tuzu; koruyucu ve asitlik düzenleyici olarak kullanılır.",
            "A salt of acetic acid used as a preservative and acidity regulator.",
            null),
        Create("E262", "Sodyum Asetatlar", "Sodium Acetates", AdditiveCategory.Preservative, 0,
            "Asetik asidin tuzları; koruyucu ve asitlik düzenleyici olarak kullanılır.",
            "Salts of acetic acid used as preservatives and acidity regulators.",
            null),
        Create("E263", "Kalsiyum Asetat", "Calcium Acetate", AdditiveCategory.Preservative, 0,
            "Asetik asidin tuzu; koruyucu olarak kullanılır.",
            "A salt of acetic acid used as a preservative.",
            null),
        Create("E270", "Laktik Asit", "Lactic Acid", AdditiveCategory.Preservative, 0,
            "Fermente gıdalarda doğal olarak oluşan ve koruyucu/asitlik düzenleyici olarak eklenen bir asit.",
            "An acid naturally formed in fermented foods and also added as a preservative/acidity regulator.",
            null),
        Create("E280", "Propiyonik Asit", "Propionic Acid", AdditiveCategory.Preservative, 0,
            "Ekmek ve unlu mamullerde küf oluşumunu önlemek için kullanılan bir koruyucu.",
            "A preservative used in bread and baked goods to inhibit mould growth.",
            null),
        Create("E281", "Sodyum Propiyonat", "Sodium Propionate", AdditiveCategory.Preservative, 0,
            "Ekmek ve unlu mamullerde küf oluşumunu önlemek için kullanılan bir koruyucu.",
            "A preservative used in bread and baked goods to inhibit mould growth.",
            null),
        Create("E282", "Kalsiyum Propiyonat", "Calcium Propionate", AdditiveCategory.Preservative, 0,
            "Ekmek ve unlu mamullerde küf oluşumunu önlemek için kullanılan bir koruyucu.",
            "A preservative used in bread and baked goods to inhibit mould growth.",
            null),
        Create("E283", "Potasyum Propiyonat", "Potassium Propionate", AdditiveCategory.Preservative, 0,
            "Ekmek ve unlu mamullerde küf oluşumunu önlemek için kullanılan bir koruyucu.",
            "A preservative used in bread and baked goods to inhibit mould growth.",
            null),
        Create("E385", "Kalsiyum Disodyum EDTA", "Calcium Disodium EDTA", AdditiveCategory.Preservative, 1,
            "Metal iyonlarını bağlayarak renk ve tat bozulmasını yavaşlatan bir koruyucu.",
            "A preservative that binds metal ions to slow colour and flavour degradation.",
            null),

        // Antioxidants (E300-E321)
        Create("E300", "Askorbik Asit (C Vitamini)", "Ascorbic Acid (Vitamin C)", AdditiveCategory.Antioxidant, 0,
            "C vitamini; antioksidan olarak oksidasyonu ve renk bozulmasını yavaşlatır.",
            "Vitamin C; used as an antioxidant to slow oxidation and colour degradation.",
            null),
        Create("E301", "Sodyum Askorbat", "Sodium Ascorbate", AdditiveCategory.Antioxidant, 0,
            "C vitamininin tuzu; antioksidan olarak kullanılır.",
            "A salt of vitamin C used as an antioxidant.",
            null),
        Create("E306", "Tokoferoller (E Vitamini)", "Tocopherols (Vitamin E)", AdditiveCategory.Antioxidant, 0,
            "Doğal kaynaklı E vitamini bileşikleri; yağların oksidasyonunu yavaşlatan antioksidanlardır.",
            "Naturally sourced vitamin E compounds; antioxidants that slow the oxidation of fats.",
            null),
        Create("E307", "Alfa-Tokoferol", "Alpha-Tocopherol", AdditiveCategory.Antioxidant, 0,
            "Sentetik E vitamini formu; antioksidan olarak kullanılır.",
            "A synthetic form of vitamin E used as an antioxidant.",
            null),
        Create("E310", "Propil Gallat", "Propyl Gallate", AdditiveCategory.Antioxidant, 1,
            "Yağ ve yağ içeren gıdalarda oksidasyonu önleyen bir antioksidan. EFSA günlük alım limiti belirlemiştir.",
            "An antioxidant that prevents oxidation in fats and fat-containing foods. EFSA has set a daily intake limit.",
            "EFSA ADI: 0.5 mg/kg vücut ağırlığı"),
        Create("E319", "TBHQ (Tersiyer Bütilhidrokinon)", "TBHQ (Tertiary Butylhydroquinone)", AdditiveCategory.Antioxidant, 2,
            "Yağların bozulmasını geciktiren sentetik bir antioksidan. EFSA günlük alım limiti belirlemiştir; yüksek dozlarla ilgili bazı hayvan çalışmaları tartışmalıdır.",
            "A synthetic antioxidant that delays fat rancidity. EFSA has set a daily intake limit; some animal studies on high-dose effects remain debated.",
            "EFSA ADI: 0.7 mg/kg vücut ağırlığı"),
        Create("E320", "BHA (Bütillenmiş Hidroksianisol)", "BHA (Butylated Hydroxyanisole)", AdditiveCategory.Antioxidant, 2,
            "Sentetik bir antioksidan. IARC tarafından 'insanlar için olası kanserojen' (Grup 2B) olarak sınıflandırılmıştır; EFSA mevcut kullanım seviyelerinde günlük alım limiti dahilinde güvenli bulmuştur.",
            "A synthetic antioxidant. Classified by IARC as 'possibly carcinogenic to humans' (Group 2B); EFSA considers it safe within its set daily intake limit at current use levels.",
            "IARC Monografları; EFSA ADI: 1 mg/kg vücut ağırlığı"),
        Create("E321", "BHT (Bütillenmiş Hidroksitoluen)", "BHT (Butylated Hydroxytoluene)", AdditiveCategory.Antioxidant, 2,
            "Sentetik bir antioksidan. EFSA günlük alım limiti belirlemiştir; bazı çalışmalarda endokrin etkileri tartışılmıştır.",
            "A synthetic antioxidant. EFSA has set a daily intake limit; endocrine effects have been discussed in some studies.",
            "EFSA ADI: 0.25 mg/kg vücut ağırlığı"),

        // Emulsifiers
        Create("E322", "Lesitin", "Lecithin", AdditiveCategory.Emulsifier, 0,
            "Genellikle soya veya ayçiçeğinden elde edilen doğal bir emülgatör.",
            "A natural emulsifier commonly derived from soy or sunflower.",
            null),
        Create("E433", "Polisorbat 80", "Polysorbate 80", AdditiveCategory.Emulsifier, 1,
            "Dondurma ve unlu mamullerde kullanılan sentetik bir emülgatör. EFSA günlük alım limiti belirlemiştir.",
            "A synthetic emulsifier used in ice cream and baked goods. EFSA has set a daily intake limit.",
            "EFSA ADI: 25 mg/kg vücut ağırlığı"),
        Create("E442", "Amonyum Fosfatidler", "Ammonium Phosphatides", AdditiveCategory.Emulsifier, 0,
            "Kakao ve çikolata ürünlerinde kullanılan bir emülgatör.",
            "An emulsifier used in cocoa and chocolate products.",
            null),
        Create("E470a", "Yağ Asitlerinin Tuzları", "Salts of Fatty Acids", AdditiveCategory.Emulsifier, 0,
            "Emülgatör ve topaklanma önleyici olarak kullanılan yağ asidi tuzları.",
            "Fatty acid salts used as an emulsifier and anti-caking agent.",
            null),
        Create("E471", "Yağ Asitlerinin Mono- ve Digliseritleri", "Mono- and Diglycerides of Fatty Acids", AdditiveCategory.Emulsifier, 0,
            "Ekmek, margarin ve birçok işlenmiş gıdada yaygın kullanılan bir emülgatör.",
            "An emulsifier widely used in bread, margarine and many processed foods.",
            null),
        Create("E472e", "Yağ Asitlerinin Mono- ve Digliseritlerinin Diasetil Tartarik Asit Esterleri (DATEM)", "DATEM", AdditiveCategory.Emulsifier, 0,
            "Ekmekçilikte hamur güçlendirici olarak kullanılan bir emülgatör.",
            "An emulsifier used in baking as a dough strengthener.",
            null),
        Create("E473", "Sükroz Yağ Asidi Esterleri", "Sucrose Esters of Fatty Acids", AdditiveCategory.Emulsifier, 0,
            "Emülgatör olarak kullanılan şeker bazlı bileşikler.",
            "Sugar-based compounds used as an emulsifier.",
            null),
        Create("E475", "Yağ Asitlerinin Poligliserol Esterleri", "Polyglycerol Esters of Fatty Acids", AdditiveCategory.Emulsifier, 0,
            "Emülgatör olarak kullanılır.",
            "Used as an emulsifier.",
            null),
        Create("E476", "Poligliserol Poliricinoleat (PGPR)", "Polyglycerol Polyricinoleate (PGPR)", AdditiveCategory.Emulsifier, 1,
            "Çikolatada viskoziteyi azaltmak için kullanılan bir emülgatör. EFSA günlük alım limiti belirlemiştir.",
            "An emulsifier used in chocolate to reduce viscosity. EFSA has set a daily intake limit.",
            "EFSA ADI: 7.5 mg/kg vücut ağırlığı"),
        Create("E477", "Propilen Glikol Yağ Asidi Esterleri", "Propylene Glycol Esters of Fatty Acids", AdditiveCategory.Emulsifier, 1,
            "Krema ve pasta karışımlarında kullanılan bir emülgatör.",
            "An emulsifier used in creams and cake mixes.",
            null),
        Create("E481", "Sodyum Stearoil Laktilat", "Sodium Stearoyl Lactylate", AdditiveCategory.Emulsifier, 0,
            "Ekmekçilikte hamuru güçlendirmek için kullanılan bir emülgatör.",
            "An emulsifier used in baking to strengthen dough.",
            null),
        Create("E491", "Sorbitan Monostearat", "Sorbitan Monostearate", AdditiveCategory.Emulsifier, 0,
            "Emülgatör olarak kullanılır.",
            "Used as an emulsifier.",
            null),
        Create("E492", "Sorbitan Tristearat", "Sorbitan Tristearate", AdditiveCategory.Emulsifier, 0,
            "Emülgatör olarak kullanılır.",
            "Used as an emulsifier.",
            null),
        Create("E495", "Sorbitan Monopalmitat", "Sorbitan Monopalmitate", AdditiveCategory.Emulsifier, 0,
            "Emülgatör olarak kullanılır.",
            "Used as an emulsifier.",
            null),

        // Thickeners / stabilizers
        Create("E400", "Aljinik Asit", "Alginic Acid", AdditiveCategory.Thickener, 0,
            "Kahverengi deniz yosunlarından elde edilen doğal bir kıvam arttırıcı.",
            "A natural thickener extracted from brown seaweed.",
            null),
        Create("E401", "Sodyum Aljinat", "Sodium Alginate", AdditiveCategory.Thickener, 0,
            "Deniz yosunundan elde edilen bir kıvam arttırıcı ve jelleştirici.",
            "A thickener and gelling agent derived from seaweed.",
            null),
        Create("E402", "Potasyum Aljinat", "Potassium Alginate", AdditiveCategory.Thickener, 0,
            "Deniz yosunundan elde edilen bir kıvam arttırıcı.",
            "A thickener derived from seaweed.",
            null),
        Create("E404", "Kalsiyum Aljinat", "Calcium Alginate", AdditiveCategory.Thickener, 0,
            "Deniz yosunundan elde edilen bir kıvam arttırıcı ve jelleştirici.",
            "A thickener and gelling agent derived from seaweed.",
            null),
        Create("E406", "Agar", "Agar", AdditiveCategory.Thickener, 0,
            "Kırmızı deniz yosunlarından elde edilen doğal bir jelleştirici.",
            "A natural gelling agent extracted from red seaweed.",
            null),
        Create("E407", "Karragenan", "Carrageenan", AdditiveCategory.Thickener, 1,
            "Deniz yosunundan elde edilen bir kıvam arttırıcı. Bazı çalışmalarda yüksek dozda sindirim sistemi rahatsızlığıyla ilişkilendirilmiştir; gıda sınıfı karragenan için EFSA mevcut kullanım seviyelerini güvenli bulmuştur.",
            "A thickener derived from seaweed. Some studies have associated high doses with digestive discomfort; EFSA considers food-grade carrageenan safe at current use levels.",
            "EFSA değerlendirmesi"),
        Create("E410", "Keçiboynuzu Gamı", "Locust Bean Gum", AdditiveCategory.Thickener, 0,
            "Keçiboynuzu tohumundan elde edilen doğal bir kıvam arttırıcı.",
            "A natural thickener derived from carob seeds.",
            null),
        Create("E412", "Guar Gamı", "Guar Gum", AdditiveCategory.Thickener, 0,
            "Guar bitkisinden elde edilen doğal bir kıvam arttırıcı.",
            "A natural thickener derived from the guar plant.",
            null),
        Create("E413", "Tragakant", "Tragacanth", AdditiveCategory.Thickener, 1,
            "Bitkisel sakızdan elde edilen bir kıvam arttırıcı; nadiren alerjik reaksiyon bildirilmiştir.",
            "A thickener derived from plant gum; allergic reactions have rarely been reported.",
            null),
        Create("E414", "Arap Gamı (Gum Arabic)", "Acacia Gum (Gum Arabic)", AdditiveCategory.Thickener, 0,
            "Akasya ağacından elde edilen doğal bir kıvam arttırıcı ve stabilizatör.",
            "A natural thickener and stabilizer derived from the acacia tree.",
            null),
        Create("E415", "Ksantan Gamı", "Xanthan Gum", AdditiveCategory.Thickener, 0,
            "Fermantasyonla üretilen doğal bir kıvam arttırıcı.",
            "A natural thickener produced through fermentation.",
            null),
        Create("E416", "Karaya Gamı", "Karaya Gum", AdditiveCategory.Thickener, 1,
            "Bitkisel sakızdan elde edilen bir kıvam arttırıcı; yüksek dozda sindirim rahatsızlığı bildirilmiştir.",
            "A thickener derived from plant gum; digestive discomfort has been reported at high doses.",
            null),
        Create("E417", "Tara Gamı", "Tara Gum", AdditiveCategory.Thickener, 0,
            "Tara ağacı tohumundan elde edilen doğal bir kıvam arttırıcı.",
            "A natural thickener derived from tara tree seeds.",
            null),
        Create("E418", "Gellan Gamı", "Gellan Gum", AdditiveCategory.Thickener, 0,
            "Fermantasyonla üretilen bir kıvam arttırıcı ve jelleştirici.",
            "A thickener and gelling agent produced through fermentation.",
            null),
        Create("E440", "Pektin", "Pectins", AdditiveCategory.Thickener, 0,
            "Meyvelerde doğal olarak bulunan, reçel ve marmelatlarda jelleştirici olarak kullanılan bir kıvam arttırıcı.",
            "A thickener naturally found in fruit, used as a gelling agent in jams and marmalades.",
            null),
        Create("E460", "Selüloz", "Cellulose", AdditiveCategory.Thickener, 0,
            "Bitki hücre duvarından elde edilen, kıvam arttırıcı ve topaklanma önleyici olarak kullanılan lif.",
            "A fibre derived from plant cell walls, used as a thickener and anti-caking agent.",
            null),
        Create("E461", "Metil Selüloz", "Methyl Cellulose", AdditiveCategory.Thickener, 0,
            "Selülozdan elde edilen bir kıvam arttırıcı.",
            "A thickener derived from cellulose.",
            null),
        Create("E463", "Hidroksipropil Selüloz", "Hydroxypropyl Cellulose", AdditiveCategory.Thickener, 0,
            "Selülozdan elde edilen bir kıvam arttırıcı.",
            "A thickener derived from cellulose.",
            null),
        Create("E464", "Hidroksipropil Metil Selüloz", "Hydroxypropyl Methyl Cellulose", AdditiveCategory.Thickener, 0,
            "Selülozdan elde edilen bir kıvam arttırıcı, sıkça glütensiz ürünlerde kullanılır.",
            "A thickener derived from cellulose, often used in gluten-free products.",
            null),
        Create("E466", "Karboksimetil Selüloz (CMC)", "Carboxymethyl Cellulose (CMC)", AdditiveCategory.Thickener, 0,
            "Selülozdan elde edilen, dondurma ve soslarda yaygın kullanılan bir kıvam arttırıcı.",
            "A cellulose-derived thickener widely used in ice cream and sauces.",
            null),

        // Acidity regulators
        Create("E296", "Malik Asit", "Malic Acid", AdditiveCategory.AcidityRegulator, 0,
            "Meyvelerde doğal olarak bulunan bir asit; asitlik düzenleyici olarak kullanılır.",
            "An acid naturally found in fruit; used as an acidity regulator.",
            null),
        Create("E297", "Fumarik Asit", "Fumaric Acid", AdditiveCategory.AcidityRegulator, 0,
            "Asitlik düzenleyici olarak kullanılan bir asit.",
            "An acid used as an acidity regulator.",
            null),
        Create("E325", "Sodyum Laktat", "Sodium Lactate", AdditiveCategory.AcidityRegulator, 0,
            "Laktik asidin tuzu; asitlik düzenleyici ve nem tutucu olarak kullanılır.",
            "A salt of lactic acid used as an acidity regulator and humectant.",
            null),
        Create("E330", "Sitrik Asit", "Citric Acid", AdditiveCategory.AcidityRegulator, 0,
            "Turunçgillerde doğal olarak bulunan, gıdalarda yaygın kullanılan bir asitlik düzenleyici.",
            "An acid naturally found in citrus fruit, widely used as an acidity regulator in food.",
            null),
        Create("E331", "Sodyum Sitratlar", "Sodium Citrates", AdditiveCategory.AcidityRegulator, 0,
            "Sitrik asidin tuzları; asitlik düzenleyici olarak kullanılır.",
            "Salts of citric acid used as an acidity regulator.",
            null),
        Create("E332", "Potasyum Sitratlar", "Potassium Citrates", AdditiveCategory.AcidityRegulator, 0,
            "Sitrik asidin tuzları; asitlik düzenleyici olarak kullanılır.",
            "Salts of citric acid used as an acidity regulator.",
            null),
        Create("E333", "Kalsiyum Sitratlar", "Calcium Citrates", AdditiveCategory.AcidityRegulator, 0,
            "Sitrik asidin tuzları; asitlik düzenleyici olarak kullanılır.",
            "Salts of citric acid used as an acidity regulator.",
            null),
        Create("E334", "Tartarik Asit", "Tartaric Acid", AdditiveCategory.AcidityRegulator, 0,
            "Üzümde doğal olarak bulunan bir asit; asitlik düzenleyici olarak kullanılır.",
            "An acid naturally found in grapes; used as an acidity regulator.",
            null),
        Create("E335", "Sodyum Tartaratlar", "Sodium Tartrates", AdditiveCategory.AcidityRegulator, 0,
            "Tartarik asidin tuzları; asitlik düzenleyici olarak kullanılır.",
            "Salts of tartaric acid used as an acidity regulator.",
            null),
        Create("E336", "Potasyum Tartaratlar (Krem Tartar)", "Potassium Tartrates (Cream of Tartar)", AdditiveCategory.AcidityRegulator, 0,
            "Şaraplarda doğal olarak oluşan, pasta yapımında kabartıcı destekleyici olarak da kullanılan bir tuz.",
            "A salt that occurs naturally in wine, also used in baking as a raising-agent support.",
            null),
        Create("E338", "Fosforik Asit", "Phosphoric Acid", AdditiveCategory.AcidityRegulator, 2,
            "Kolalı içeceklerde yaygın kullanılan bir asitlik düzenleyici. Yüksek toplam fosfat alımı bazı çalışmalarda kemik ve kardiyovasküler sağlıkla ilişkilendirilmiştir; EFSA günlük alım limiti belirlemiştir.",
            "An acidity regulator widely used in cola drinks. High total phosphate intake has been linked to bone and cardiovascular health in some studies; EFSA has set a daily intake limit.",
            "EFSA ADI: 40 mg/kg vücut ağırlığı (toplam fosfat)"),
        Create("E339", "Sodyum Fosfatlar", "Sodium Phosphates", AdditiveCategory.AcidityRegulator, 2,
            "İşlenmiş et ve peynirlerde kullanılan asitlik düzenleyici/emülgatör tuzları. EFSA toplam fosfat alımı için günlük limit belirlemiştir.",
            "Acidity regulator/emulsifier salts used in processed meat and cheese. EFSA has set a daily intake limit for total phosphate intake.",
            "EFSA ADI: 40 mg/kg vücut ağırlığı (toplam fosfat)"),
        Create("E340", "Potasyum Fosfatlar", "Potassium Phosphates", AdditiveCategory.AcidityRegulator, 2,
            "İşlenmiş gıdalarda kullanılan asitlik düzenleyici tuzları. EFSA toplam fosfat alımı için günlük limit belirlemiştir.",
            "Acidity regulator salts used in processed foods. EFSA has set a daily intake limit for total phosphate intake.",
            "EFSA ADI: 40 mg/kg vücut ağırlığı (toplam fosfat)"),
        Create("E341", "Kalsiyum Fosfatlar", "Calcium Phosphates", AdditiveCategory.AcidityRegulator, 1,
            "Kabartıcı ve mineral takviyesi amacıyla kullanılan fosfat tuzları.",
            "Phosphate salts used as raising agents and mineral fortification.",
            null),
        Create("E343", "Magnezyum Fosfatlar", "Magnesium Phosphates", AdditiveCategory.AcidityRegulator, 1,
            "Asitlik düzenleyici ve topaklanma önleyici olarak kullanılan fosfat tuzları.",
            "Phosphate salts used as an acidity regulator and anti-caking agent.",
            null),
        Create("E350", "Sodyum Malatlar", "Sodium Malates", AdditiveCategory.AcidityRegulator, 0,
            "Malik asidin tuzları; asitlik düzenleyici olarak kullanılır.",
            "Salts of malic acid used as an acidity regulator.",
            null),
        Create("E355", "Adipik Asit", "Adipic Acid", AdditiveCategory.AcidityRegulator, 0,
            "Asitlik düzenleyici olarak kullanılan bir asit.",
            "An acid used as an acidity regulator.",
            null),
        Create("E363", "Süksinik Asit", "Succinic Acid", AdditiveCategory.AcidityRegulator, 0,
            "Asitlik düzenleyici olarak kullanılan bir asit.",
            "An acid used as an acidity regulator.",
            null),
        Create("E500", "Sodyum Karbonatlar", "Sodium Carbonates", AdditiveCategory.AcidityRegulator, 0,
            "Kabartıcı ve asitlik düzenleyici olarak kullanılır; karbonatlı içeceklerde de bulunur.",
            "Used as a raising agent and acidity regulator; also present in carbonated drinks.",
            null),
        Create("E501", "Potasyum Karbonatlar", "Potassium Carbonates", AdditiveCategory.AcidityRegulator, 0,
            "Asitlik düzenleyici ve kabartıcı olarak kullanılır.",
            "Used as an acidity regulator and raising agent.",
            null),
        Create("E503", "Amonyum Karbonatlar", "Ammonium Carbonates", AdditiveCategory.AcidityRegulator, 0,
            "Geleneksel bisküvi tariflerinde kullanılan bir kabartıcı.",
            "A raising agent used in traditional biscuit recipes.",
            null),
        Create("E507", "Hidroklorik Asit", "Hydrochloric Acid", AdditiveCategory.AcidityRegulator, 0,
            "Sınırlı miktarda asitlik düzenleyici olarak kullanılan bir işlem yardımcı maddesi.",
            "A processing aid used in limited amounts as an acidity regulator.",
            null),
        Create("E508", "Potasyum Klorür", "Potassium Chloride", AdditiveCategory.AcidityRegulator, 0,
            "Sofra tuzu yerine geçen ürünlerde ve kıvam arttırıcı olarak kullanılan bir mineral tuz.",
            "A mineral salt used in salt-substitute products and as a gelling agent.",
            null),
        Create("E509", "Kalsiyum Klorür", "Calcium Chloride", AdditiveCategory.AcidityRegulator, 0,
            "Sertleştirici ve stabilizatör olarak kullanılan bir mineral tuz.",
            "A mineral salt used as a firming agent and stabilizer.",
            null),
        Create("E511", "Magnezyum Klorür", "Magnesium Chloride", AdditiveCategory.AcidityRegulator, 0,
            "Tofu üretiminde pıhtılaştırıcı olarak kullanılan bir mineral tuz.",
            "A mineral salt used as a coagulant in tofu production.",
            null),
        Create("E574", "Glukonik Asit", "Gluconic Acid", AdditiveCategory.AcidityRegulator, 0,
            "Asitlik düzenleyici olarak kullanılan bir asit.",
            "An acid used as an acidity regulator.",
            null),
        Create("E575", "Glukono Delta-Lakton", "Glucono Delta-Lactone", AdditiveCategory.AcidityRegulator, 0,
            "Et ürünlerinde ve tofu üretiminde kullanılan bir asitlik düzenleyici.",
            "An acidity regulator used in meat products and tofu production.",
            null),
        Create("E576", "Sodyum Glukonat", "Sodium Gluconate", AdditiveCategory.AcidityRegulator, 0,
            "Glukonik asidin tuzu; sekestran olarak kullanılır.",
            "A salt of gluconic acid used as a sequestrant.",
            null),
        Create("E577", "Potasyum Glukonat", "Potassium Gluconate", AdditiveCategory.AcidityRegulator, 0,
            "Glukonik asidin tuzu; asitlik düzenleyici olarak kullanılır.",
            "A salt of gluconic acid used as an acidity regulator.",
            null),
        Create("E578", "Kalsiyum Glukonat", "Calcium Gluconate", AdditiveCategory.AcidityRegulator, 0,
            "Glukonik asidin tuzu; sertleştirici olarak kullanılır.",
            "A salt of gluconic acid used as a firming agent.",
            null),

        // Flavour enhancers
        Create("E620", "Glutamik Asit", "Glutamic Acid", AdditiveCategory.FlavourEnhancer, 1,
            "Doğal olarak birçok gıdada bulunan bir amino asit; lezzet arttırıcı olarak kullanılır.",
            "An amino acid naturally present in many foods; used as a flavour enhancer.",
            null),
        Create("E621", "Monosodyum Glutamat (MSG)", "Monosodium Glutamate (MSG)", AdditiveCategory.FlavourEnhancer, 1,
            "Yaygın kullanılan bir lezzet arttırıcı. Bazı bireylerde geçici baş ağrısı gibi semptomlar bildirilmiştir, ancak kontrollü çalışmalar bu ilişkiyi doğrulamamıştır; JECFA günlük alım sınırı belirtmemiştir.",
            "A widely used flavour enhancer. Some individuals have reported transient symptoms such as headache, though controlled studies have not confirmed the link; JECFA has not specified a daily intake limit.",
            "JECFA ADI: belirtilmemiş"),
        Create("E622", "Monopotasyum Glutamat", "Monopotassium Glutamate", AdditiveCategory.FlavourEnhancer, 1,
            "MSG'ye benzer şekilde kullanılan bir lezzet arttırıcı.",
            "A flavour enhancer used similarly to MSG.",
            null),
        Create("E623", "Kalsiyum Diglutamat", "Calcium Diglutamate", AdditiveCategory.FlavourEnhancer, 1,
            "Lezzet arttırıcı olarak kullanılır.",
            "Used as a flavour enhancer.",
            null),
        Create("E627", "Disodyum Guanilat", "Disodium Guanylate", AdditiveCategory.FlavourEnhancer, 1,
            "Genellikle MSG ile birlikte kullanılan bir lezzet arttırıcı.",
            "A flavour enhancer often used alongside MSG.",
            null),
        Create("E631", "Disodyum İnosinat", "Disodium Inosinate", AdditiveCategory.FlavourEnhancer, 1,
            "Genellikle MSG ile birlikte kullanılan bir lezzet arttırıcı.",
            "A flavour enhancer often used alongside MSG.",
            null),
        Create("E635", "Disodyum 5'-Ribonükleotidler", "Disodium 5'-Ribonucleotides", AdditiveCategory.FlavourEnhancer, 1,
            "Genellikle MSG ile birlikte kullanılan bir lezzet arttırıcı karışımı.",
            "A flavour enhancer blend often used alongside MSG.",
            null),

        // Sweeteners
        Create("E420", "Sorbitol", "Sorbitol", AdditiveCategory.Sweetener, 1,
            "Şeker alkolü grubunda bir tatlandırıcı. AB mevzuatına göre aşırı tüketiminin laksatif etki yapabileceği etikette belirtilmelidir.",
            "A sugar alcohol sweetener. EU regulation requires labelling that excessive consumption may have a laxative effect.",
            "AB Yönetmeliği 1333/2008"),
        Create("E421", "Mannitol", "Mannitol", AdditiveCategory.Sweetener, 1,
            "Şeker alkolü grubunda bir tatlandırıcı. AB mevzuatına göre aşırı tüketiminin laksatif etki yapabileceği etikette belirtilmelidir.",
            "A sugar alcohol sweetener. EU regulation requires labelling that excessive consumption may have a laxative effect.",
            "AB Yönetmeliği 1333/2008"),
        Create("E950", "Asesülfam K", "Acesulfame K", AdditiveCategory.Sweetener, 1,
            "Kalorisiz sentetik bir tatlandırıcı. EFSA günlük alım limiti belirlemiştir.",
            "A calorie-free synthetic sweetener. EFSA has set a daily intake limit.",
            "EFSA ADI: 9 mg/kg vücut ağırlığı"),
        Create("E951", "Aspartam", "Aspartame", AdditiveCategory.Sweetener, 2,
            "Kalorisiz sentetik bir tatlandırıcı. 2023 yılında IARC aspartamı 'insanlar için olası kanserojen' (Grup 2B) olarak sınıflandırmış, aynı yıl JECFA mevcut günlük alım limitini değiştirmemiştir. Fenilketonürisi olan bireyler için fenilalanin kaynağı içerdiği etikette belirtilmelidir.",
            "A calorie-free synthetic sweetener. In 2023 IARC classified aspartame as 'possibly carcinogenic to humans' (Group 2B), while JECFA maintained the existing daily intake limit the same year. Labelling must state it contains a source of phenylalanine for people with phenylketonuria.",
            "IARC 2023; JECFA ADI: 40 mg/kg vücut ağırlığı"),
        Create("E952", "Siklamat", "Cyclamate", AdditiveCategory.Sweetener, 1,
            "Kalorisiz sentetik bir tatlandırıcı. Geçmişte hayvan çalışmalarında yüksek dozlarla ilgili endişeler gündeme gelmiş, ancak EFSA mevcut ADI dahilinde güvenli bulmuştur.",
            "A calorie-free synthetic sweetener. Concerns about high-dose animal studies arose historically, but EFSA considers it safe within its current ADI.",
            "EFSA ADI: 7 mg/kg vücut ağırlığı"),
        Create("E954", "Sakarin", "Saccharin", AdditiveCategory.Sweetener, 1,
            "Kalorisiz sentetik bir tatlandırıcı. Geçmişte hayvan çalışmalarında endişeler gündeme gelmiş, sonraki değerlendirmelerde insanlar için geçerli bulunmamıştır; EFSA günlük alım limiti belirlemiştir.",
            "A calorie-free synthetic sweetener. Concerns raised by historical animal studies were later found not applicable to humans; EFSA has set a daily intake limit.",
            "EFSA ADI: 5 mg/kg vücut ağırlığı"),
        Create("E955", "Sükraloz", "Sucralose", AdditiveCategory.Sweetener, 1,
            "Şekerden üretilen kalorisiz sentetik bir tatlandırıcı. EFSA günlük alım limiti belirlemiştir.",
            "A calorie-free synthetic sweetener produced from sugar. EFSA has set a daily intake limit.",
            "EFSA ADI: 15 mg/kg vücut ağırlığı"),
        Create("E960", "Steviol Glikozitleri (Stevia)", "Steviol Glycosides (Stevia)", AdditiveCategory.Sweetener, 0,
            "Stevia bitkisinden elde edilen doğal, kalorisiz bir tatlandırıcı.",
            "A natural, calorie-free sweetener extracted from the stevia plant.",
            null),
        Create("E961", "Neotam", "Neotame", AdditiveCategory.Sweetener, 1,
            "Yüksek yoğunluklu sentetik bir tatlandırıcı. EFSA günlük alım limiti belirlemiştir.",
            "A high-intensity synthetic sweetener. EFSA has set a daily intake limit.",
            "EFSA ADI: 2 mg/kg vücut ağırlığı"),
        Create("E962", "Aspartam-Asesülfam Tuzu", "Salt of Aspartame-Acesulfame", AdditiveCategory.Sweetener, 2,
            "Aspartam ve asesülfam K bileşiminden oluşan bir tatlandırıcı; aspartam bileşenine ilişkin uyarılar geçerlidir.",
            "A sweetener formed from a combination of aspartame and acesulfame K; the warnings applicable to aspartame also apply.",
            null),
        Create("E965", "Maltitol", "Maltitol", AdditiveCategory.Sweetener, 1,
            "Şeker alkolü grubunda bir tatlandırıcı. AB mevzuatına göre aşırı tüketiminin laksatif etki yapabileceği etikette belirtilmelidir.",
            "A sugar alcohol sweetener. EU regulation requires labelling that excessive consumption may have a laxative effect.",
            "AB Yönetmeliği 1333/2008"),
        Create("E966", "Laktitol", "Lactitol", AdditiveCategory.Sweetener, 1,
            "Şeker alkolü grubunda bir tatlandırıcı. AB mevzuatına göre aşırı tüketiminin laksatif etki yapabileceği etikette belirtilmelidir.",
            "A sugar alcohol sweetener. EU regulation requires labelling that excessive consumption may have a laxative effect.",
            "AB Yönetmeliği 1333/2008"),
        Create("E967", "Ksilitol", "Xylitol", AdditiveCategory.Sweetener, 1,
            "Şeker alkolü grubunda bir tatlandırıcı, sıkça sakızlarda kullanılır. AB mevzuatına göre aşırı tüketiminin laksatif etki yapabileceği etikette belirtilmelidir.",
            "A sugar alcohol sweetener, often used in chewing gum. EU regulation requires labelling that excessive consumption may have a laxative effect.",
            "AB Yönetmeliği 1333/2008"),
        Create("E968", "Eritritol", "Erythritol", AdditiveCategory.Sweetener, 0,
            "Şeker alkolü grubunda, diğerlerine kıyasla sindirim sistemi etkisi daha düşük olan bir tatlandırıcı.",
            "A sugar alcohol sweetener with a lower digestive impact compared to others in its group.",
            null),

        // Other
        Create("E422", "Gliserol", "Glycerol", AdditiveCategory.Other, 0,
            "Nem tutucu ve çözücü olarak kullanılan doğal bir bileşik.",
            "A naturally occurring compound used as a humectant and solvent.",
            null),
        Create("E551", "Silikon Dioksit", "Silicon Dioxide", AdditiveCategory.Other, 0,
            "Toz ve granül gıdalarda topaklanmayı önlemek için kullanılan bir mineral.",
            "A mineral used to prevent caking in powdered and granulated foods.",
            null),
        Create("E553b", "Talk", "Talc", AdditiveCategory.Other, 1,
            "Sakız ve şekerlemelerde topaklanma önleyici olarak kullanılan bir mineral; kullanım alanı sınırlıdır.",
            "A mineral used as an anti-caking agent in chewing gum and confectionery, with restricted permitted uses.",
            null),
        Create("E901", "Arı Balmumu", "Beeswax", AdditiveCategory.Other, 0,
            "Şekerleme ve meyvelerde parlatıcı olarak kullanılan doğal bir madde; vegan değildir.",
            "A natural substance used as a glazing agent on confectionery and fruit; not vegan.",
            null),
        Create("E903", "Karnauba Balmumu", "Carnauba Wax", AdditiveCategory.Other, 0,
            "Karnauba palmiyesinden elde edilen doğal bir parlatıcı.",
            "A natural glazing agent derived from the carnauba palm.",
            null),
        Create("E904", "Şellak", "Shellac", AdditiveCategory.Other, 1,
            "Böcek salgısından elde edilen doğal bir parlatıcı; vegan değildir.",
            "A natural glazing agent derived from insect secretions; not vegan.",
            null),
        Create("E941", "Azot", "Nitrogen", AdditiveCategory.Other, 0,
            "Ambalajlı gıdalarda koruyucu atmosfer sağlamak için kullanılan bir gaz.",
            "A gas used to create a protective atmosphere in packaged food.",
            null),
        Create("E942", "Diazot Monoksit", "Nitrous Oxide", AdditiveCategory.Other, 1,
            "Krem şantilerde itici gaz olarak kullanılır.",
            "Used as a propellant gas in whipped cream products.",
            null),
        };

        foreach (var additive in additives)
        {
            if (SynonymOverrides.TryGetValue(additive.Code, out var synonyms))
            {
                additive.Synonyms = JsonSerializer.Serialize(synonyms);
            }
        }

        return additives;
    }

    private static Additive Create(
        string code,
        string nameTr,
        string nameEn,
        AdditiveCategory category,
        int riskLevel,
        string descriptionTr,
        string descriptionEn,
        string? sourceNote) => new()
    {
        Code = code,
        NameTr = nameTr,
        NameEn = nameEn,
        Category = category,
        RiskLevel = riskLevel,
        DescriptionTr = descriptionTr,
        DescriptionEn = descriptionEn,
        SourceNote = sourceNote
    };
}
